camunda.bpm:
  admin-user:
    id: ${CAMUNDA_ADMIN_USER_ID}
    password: ${CAMUNDA_ADMIN_USER_PASSWORD}
    firstName: ${CAMUNDA_ADMIN_USER_FIRST_NAME}
    lastName: ${CAMUNDA_ADMIN_USER_LAST_NAME}
  filter:
    create: All tasks